Check host name before backup

diff --git a/bin/backup-github b/bin/backup-github
--- a/bin/backup-github
+++ b/bin/backup-github
@@ -5,12 +5,14 @@
 #  - sync files to remote storage (NAS mounted with GVfs/Samba)
 #
 # requires:
-#  - gvfs-backends (apt install)
-#  - githubtakeout (pipx install)
-#  - rsync (apt install)
+#  - gvfs-backends
+#  - rsync
+#  - githubtakeout
 
 set -e
 
+
+EXPECTED_HOST="penguin"
 NAS_HOST="bitz"
 NAS_IP="10.0.0.5"
 NAS_USERNAME="cgoldberg"
@@ -32,6 +34,13 @@ die () {
 ok () {
     tput bold; tput setaf 10; echo -en "\u2714  " 1>&2; tput sgr0
     tput bold; echo "$*" 1>&2; tput sgr0
+}
+
+check_host () {
+    if [ "${HOSTNAME}" != "${EXPECTED_HOST}" ]; then
+        die "fatal: can't run on this host: ${HOSTNAME}" \
+            "(required: ${EXPECTED_HOST})"
+    fi
 }
 
 check_configuration () {
@@ -62,11 +71,13 @@ delete_old_backups () {
 }
 
 mount_nas () {
-    gio mount --unmount "smb://${NAS_USERNAME}@${NAS_IP}/${NAS_SHARE}" 2>/dev/null || true
+    gio mount --unmount "smb://${NAS_USERNAME}@${NAS_IP}/${NAS_SHARE}" \
+        2>/dev/null || true
     gio mount "smb://${NAS_USERNAME}@${NAS_IP}/${NAS_SHARE}"
     ln -s \
-        "/run/user/1000/gvfs/smb-share:server=${NAS_IP},share=${NAS_SHARE},user=${NAS_USERNAME}" \
-        ~/"${NAS_HOST}" \
+        "/run/user/1000/gvfs/smb-share:server=${NAS_IP}," \
+        "share=${NAS_SHARE},user=${NAS_USERNAME}" \
+        "${HOME}/${NAS_HOST}" \
         2>/dev/null || true
     until [ -d "${BACKUP_DESTINATION_PATH}" ]; do
         sleep .5
@@ -85,7 +96,7 @@ timer () {
     local hours=$((duration / 3600))
     local minutes=$(((duration % 3600) / 60))
     local seconds=$((duration % 60))
-    printf  -v elapsed_time "%02d:%02d:%02d" "${hours}" "${minutes}" "${seconds}"
+    printf -v elapsed_time "%02d:%02d:%02d" "${hours}" "${minutes}" "${seconds}"
 }
 
 do_backup () {
@@ -121,6 +132,7 @@ do_backup () {
     sync "${BACKUP_DESTINATION_PATH}"
 }
 
+check_host
 echo
 echo "mounting remote storage ..."
 mount_nas
diff --git a/bin/backup-nas-to-external b/bin/backup-nas-to-external
--- a/bin/backup-nas-to-external
+++ b/bin/backup-nas-to-external
@@ -5,10 +5,13 @@
 #  - insert external drive, in 'Files' app right-click 'backup' directory and 'Share with Linux'
 #
 # requires:
-#  - gvfs-backends (apt install)
-#  - rsync (apt install)
+#  - gvfs-backends
+#  - rsync
 
 set -e
+
+
+EXPECTED_HOST="penguin"
 
 NAS_USERNAME="cgoldberg"
 NAS_SHARE="public"
@@ -34,6 +37,13 @@ ok () {
     tput bold; echo "$*" 1>&2; tput sgr0
 }
 
+check_host () {
+    if [ "${HOSTNAME}" != "${EXPECTED_HOST}" ]; then
+        die "fatal: can't run on this host: ${HOSTNAME}" \
+            "(required: ${EXPECTED_HOST})"
+    fi
+}
+
 check_configuration () {
     if [ ! -d "${SOURCE_PATH}" ]; then
         die "fatal: can't find mounted storage: ${SOURCE_PATH}"
@@ -49,10 +59,12 @@ check_configuration () {
 }
 
 mount_source_nas () {
-    gio mount --unmount "smb://${NAS_USERNAME}@${SOURCE_NAS_IP}/${NAS_SHARE}" 2>/dev/null || true
+    gio mount --unmount "smb://${NAS_USERNAME}@${SOURCE_NAS_IP}/${NAS_SHARE}" \
+        2>/dev/null || true
     gio mount "smb://${NAS_USERNAME}@${SOURCE_NAS_IP}/${NAS_SHARE}"
     ln -s \
-        "/run/user/1000/gvfs/smb-share:server=${SOURCE_NAS_IP},share=${NAS_SHARE},user=${NAS_USERNAME}" \
+        "/run/user/1000/gvfs/smb-share:server=${SOURCE_NAS_IP}," \
+        "share=${NAS_SHARE},user=${NAS_USERNAME}" \
         ~/"${SOURCE_NAS_HOST}" \
         2>/dev/null || true
     until [ -d "${SOURCE_PATH}" ]; do
@@ -72,7 +84,7 @@ timer () {
     local hours=$((duration / 3600))
     local minutes=$(((duration % 3600) / 60))
     local seconds=$((duration % 60))
-    printf  -v elapsed_time "%02d:%02d:%02d" "${hours}" "${minutes}" "${seconds}"
+    printf -v elapsed_time "%02d:%02d:%02d" "${hours}" "${minutes}" "${seconds}"
 }
 
 do_backup () {
@@ -103,6 +115,7 @@ do_backup () {
     sync "${DESTINATION_PATH}"
 }
 
+check_host
 echo
 echo "mounting remote storage source ..."
 mount_source_nas
diff --git a/bin/backup-nas-to-nas b/bin/backup-nas-to-nas
--- a/bin/backup-nas-to-nas
+++ b/bin/backup-nas-to-nas
@@ -4,10 +4,13 @@
 #  - sync files from source NAS to destination NAS (mounted with GVfs/Samba)
 #
 # requires:
-#  - gvfs-backends (apt install)
-#  - rsync (apt install)
+#  - gvfs-backends
+#  - rsync
 
 set -e
+
+
+EXPECTED_HOST="penguin"
 
 NAS_USERNAME="cgoldberg"
 NAS_SHARE="public"
@@ -35,6 +38,13 @@ ok () {
     tput bold; echo "$*" 1>&2; tput sgr0
 }
 
+check_host () {
+    if [ "${HOSTNAME}" != "${EXPECTED_HOST}" ]; then
+        die "fatal: can't run on this host: ${HOSTNAME}" \
+            "(required: ${EXPECTED_HOST})"
+    fi
+}
+
 check_configuration () {
     if [ ! -d "${SOURCE_PATH}" ]; then
         die "fatal: can't find mounted storage: ${SOURCE_PATH}"
@@ -50,11 +60,13 @@ check_configuration () {
 }
 
 mount_source_nas () {
-    gio mount --unmount "smb://${NAS_USERNAME}@${SOURCE_NAS_IP}/${NAS_SHARE}" 2>/dev/null || true
+    gio mount --unmount "smb://${NAS_USERNAME}@${SOURCE_NAS_IP}/${NAS_SHARE}" \
+        2>/dev/null || true
     gio mount "smb://${NAS_USERNAME}@${SOURCE_NAS_IP}/${NAS_SHARE}"
     ln -s \
-        "/run/user/1000/gvfs/smb-share:server=${SOURCE_NAS_IP},share=${NAS_SHARE},user=${NAS_USERNAME}" \
-        ~/"${SOURCE_NAS_HOST}" \
+        "/run/user/1000/gvfs/smb-share:server=${SOURCE_NAS_IP}," \
+        "share=${NAS_SHARE},user=${NAS_USERNAME}" \
+        "${HOME}/${SOURCE_NAS_HOST}" \
         2>/dev/null || true
     until [ -d "${SOURCE_PATH}" ]; do
         sleep .5
@@ -62,11 +74,13 @@ mount_source_nas () {
 }
 
 mount_destination_nas () {
-    gio mount --unmount "smb://${NAS_USERNAME}@${DESTINATION_NAS_IP}/${NAS_SHARE}" 2>/dev/null || true
+    gio mount --unmount "smb://${NAS_USERNAME}@${DESTINATION_NAS_IP}/${NAS_SHARE}" \
+        2>/dev/null || true
     gio mount "smb://${NAS_USERNAME}@${DESTINATION_NAS_IP}/${NAS_SHARE}"
     ln -s \
-        "/run/user/1000/gvfs/smb-share:server=${DESTINATION_NAS_IP},share=${NAS_SHARE},user=${NAS_USERNAME}" \
-        ~/"${DESTINATION_NAS_HOST}" \
+        "/run/user/1000/gvfs/smb-share:server=${DESTINATION_NAS_IP}," \
+        "share=${NAS_SHARE},user=${NAS_USERNAME}" \
+        "${HOME}/${DESTINATION_NAS_HOST}" \
         2>/dev/null || true
     until [ -d "${DESTINATION_PATH}" ]; do
         sleep .5
@@ -89,7 +103,7 @@ timer () {
     local hours=$((duration / 3600))
     local minutes=$(((duration % 3600) / 60))
     local seconds=$((duration % 60))
-    printf  -v elapsed_time "%02d:%02d:%02d" "${hours}" "${minutes}" "${seconds}"
+    printf -v elapsed_time "%02d:%02d:%02d" "${hours}" "${minutes}" "${seconds}"
 }
 
 do_backup () {
@@ -118,6 +132,7 @@ do_backup () {
     sync "${DESTINATION_PATH}"
 }
 
+check_host
 echo
 echo "mounting remote storage source ..."
 mount_source_nas
