Overhaul backup script to use NAS storage instead of Dropbox

diff --git a/bin/backup-all b/bin/backup-all
--- a/bin/backup-all
+++ b/bin/backup-all
@@ -2,19 +2,25 @@
 #
 # general backup script:
 #  - download Google Drive files
-#  - download public GitHub repos
-#  - create a tarball
-#  - upload tarball to Google Drive and Dropbox
+#  - download public GitHub repos as trarballs
+#  - rsync files to remote storage
 #
 # requires:
+#  - gvfs-backends (apt install)
 #  - google-drive-export (PyPI)
 #  - githubtakeout (PyPI)
-#  - rclone (apt install) with remotes configured: gdrive, dbox
 
 set -e
 
-BACKUP_DIR="${HOME}/backup"
-BACKUP_ARCHIVE="backups.tar.gz"
+NAS_HOST="bitz"
+NAS_IP="10.0.0.5"
+NAS_USERNAME="cgoldberg"
+NAS_SHARE="public"
+BACKUP_LOCAL_PATH="${HOME}/backup"
+BACKUP_DESTINATION_PATH="${HOME}/${NAS_HOST}"
+GOOGLE_DRIVE_BACKUP_DIR="GoogleDrive_Backup"
+GITHUB_BACKUP_DIR="GitHub_Backup"
+SEP="----------------------------------------------------------------"
 
 die () {
     tput bold; tput setaf 1; echo -en "\u2717 " 1>&2; tput sgr0
@@ -27,58 +33,139 @@ ok () {
     tput bold; echo "$*" 1>&2; tput sgr0
 }
 
-if [ ! "${BACKUP_DIR}" ]; then
-    die "backup directory not found"
-fi
+check_configuration () {
+    if [ ! -d "${BACKUP_LOCAL_PATH}" ]; then
+        die "fatal: backup directory not found: ${BACKUP_LOCAL_PATH}"
+    fi
 
-if [ ! -x "$(command -v google_drive_export)" ]; then
-    die "google_drive_export not found"
-fi
+    if [ ! -d "${BACKUP_DESTINATION_PATH}" ]; then
+        die "fatal: can't find mounted storage: ${BACKUP_DESTINATION_PATH}"
+    fi
 
-if [ ! -x "$(command -v githubtakeout)" ]; then
-    die "githubtakeout not found"
-fi
+    if [ ! -x "$(type -pP rsync)" ]; then
+        die "fatal: rsync not found"
+    fi
+
+    if [ ! -x "$(type -pP google_drive_export)" ]; then
+        die "fatal: google_drive_export not found"
+    fi
+
+    if [ ! -x "$(type -pP githubtakeout)" ]; then
+        die "fatal: githubtakeout not found"
+    fi
+}
+
+delete_old_backups () {
+    echo "deleting old backup files and directories ..."
+    rm -rf ./exported_files
+    rm -rf ./backups
+    rm -rf "./${GOOGLE_DRIVE_BACKUP_DIR}"
+    rm -rf "./${GITHUB_BACKUP_DIR}"
+}
+
+mount_nas () {
+    gio mount --unmount "smb://${NAS_USERNAME}@${NAS_IP}/${NAS_SHARE}" 2>/dev/null || true
+    gio mount "smb://${NAS_USERNAME}@${NAS_IP}/${NAS_SHARE}"
+    ln -s \
+        "/run/user/1000/gvfs/smb-share:server=${NAS_IP},share=${NAS_SHARE},user=${NAS_USERNAME}" \
+        ~/"${NAS_HOST}" \
+        2>/dev/null || true
+    until [ -d "${BACKUP_DESTINATION_PATH}" ]; do
+        sleep .5
+    done
+}
+
+unmount_nas () {
+    gio mount --unmount "smb://${NAS_USERNAME}@${NAS_IP}/${NAS_SHARE}"
+}
+
+timer () {
+    local start_time=${SECONDS}
+    "$@"
+    local end_time=${SECONDS}
+    local duration=$((end_time - start_time))
+    local hours=$((duration / 3600))
+    local minutes=$(((duration % 3600) / 60))
+    local seconds=$((duration % 60))
+    printf  -v elapsed_time "%02d:%02d:%02d" "${hours}" "${minutes}" "${seconds}"
+}
+
+do_backup () {
+    echo "downloading Google Drive backup ..."
+    echo
+    google_drive_export
+    echo
+    echo "${SEP}"
+    echo
+    echo "downloading GitHub backup ..."
+    echo
+    githubtakeout "${GITHUB_USERNAME}" --format=tar
+    echo
+    echo "${SEP}"
+    mv ./exported_files "./${GOOGLE_DRIVE_BACKUP_DIR}"
+    mv ./backups "./${GITHUB_BACKUP_DIR}"
+    sync "${BACKUP_LOCAL_PATH}"
+    echo
+    echo "syncing "\
+        "${BACKUP_LOCAL_PATH}/${GOOGLE_DRIVE_BACKUP_DIR} to "\
+        "${BACKUP_DESTINATION_PATH}/${GOOGLE_DRIVE_BACKUP_DIR} ..."
+    echo
+    rsync \
+        --delete \
+        --human-readable \
+        --links \
+        --progress \
+        --recursive \
+        --safe-links \
+        --stats \
+        --times \
+        --verbose \
+        "${BACKUP_LOCAL_PATH}/${GOOGLE_DRIVE_BACKUP_DIR}/" \
+        "${BACKUP_DESTINATION_PATH}/${GOOGLE_DRIVE_BACKUP_DIR}/"
+    echo
+    echo "${SEP}"
+    echo
+    echo "syncing "\
+        "${BACKUP_LOCAL_PATH}/${GITHUB_BACKUP_DIR} to "\
+        "${BACKUP_DESTINATION_PATH}/${GITHUB_BACKUP_DIR} ..."
+    echo
+    rsync \
+        --delete \
+        --human-readable \
+        --links \
+        --progress \
+        --recursive \
+        --safe-links \
+        --stats \
+        --times \
+        --verbose \
+        "${BACKUP_LOCAL_PATH}/${GITHUB_BACKUP_DIR}/" \
+        "${BACKUP_DESTINATION_PATH}/${GITHUB_BACKUP_DIR}/"
+    sync "${BACKUP_DESTINATION_PATH}"
+}
 
 echo
-echo "changing directory to: ${BACKUP_DIR}"
+echo "mounting remote storage ..."
+mount_nas
+echo "verifying configuration ..."
+check_configuration
+echo "changing directory to: ${BACKUP_LOCAL_PATH}"
+cd "${BACKUP_LOCAL_PATH}"
+echo "deleting old local backups ..."
+delete_old_backups
+echo "starting backup job ..."
 echo
-cd "${BACKUP_DIR}"
-
-echo "deleting old backup files and directories ..."
-rm -f "./${BACKUP_ARCHIVE}"
-rm -rf ./exported_files
-rm -rf ./backups
-rm -rf ./google_drive_files
-rm -rf ./github_archives
-
-google_drive_export
-rm -f "${BACKUP_DIR}/exported_files/${BACKUP_ARCHIVE}"
+echo "${SEP}"
 echo
-
-githubtakeout "${GITHUB_USERNAME}" --format=tar
+timer do_backup
 echo
-
-mv ./exported_files ./google_drive_files
-mv ./backups ./github_archives
-tar cvzf "./${BACKUP_ARCHIVE}" ./*
+echo "${SEP}"
 echo
-
-if [ ! -x "$(command -v rclone)" ]; then
-    cd "${OLDPWD}"
-    die "rclone not found"
-fi
-
-echo "uploading archive to Google Drive ..."
-echo
-rclone copyto "./${BACKUP_ARCHIVE}" "gdrive:/${BACKUP_ARCHIVE}" --progress
-echo
-
-echo "uploading archive to Dropbox ..."
-echo
-rclone copyto "./${BACKUP_ARCHIVE}" "dbox:/${BACKUP_ARCHIVE}" --progress
-echo
-
+echo "unmounting remote storage ..."
+unmount_nas
 echo "changing directory back to: ${OLDPWD}"
 cd "${OLDPWD}"
+echo
+echo "elapsed time: ${elapsed_time}"
 echo
 ok "backup complete!"
