Fix trap signal handling

diff --git a/bin/backup-nas-to-external b/bin/backup-nas-to-external
--- a/bin/backup-nas-to-external
+++ b/bin/backup-nas-to-external
@@ -9,7 +9,7 @@
 # requires:
 #  - rsync
 
-trap 'echo -e "\nAborted"; exit 1' INT
+trap cleanup SIGINT SIGTERM
 
 
 EXPECTED_HOSTS=("minime" "raspberrypi")
@@ -30,6 +30,12 @@ die () {
 ok () {
     tput bold; tput setaf 10; echo -en "\u2714  " 1>&2; tput sgr0
     tput bold; echo "$*" 1>&2; tput sgr0
+}
+
+cleanup () {
+    echo
+    eject_usb
+    die "Aborted"
 }
 
 check_host () {
@@ -64,6 +70,7 @@ diskspace () {
 }
 
 eject_usb () {
+    sync
     local partition=$(findmnt -rno SOURCE "${USB_MNT}")
     local device_name=$(lsblk -rno PKNAME "${partition}")
     local disk="/dev/${device_name}"
diff --git a/bin/backup-nas-to-nas b/bin/backup-nas-to-nas
--- a/bin/backup-nas-to-nas
+++ b/bin/backup-nas-to-nas
@@ -11,7 +11,7 @@
 #  - rsync
 # - 'sync-nas' script
 
-trap 'echo -e "\nAborted"; exit 1' INT
+trap cleanup SIGINT SIGTERM
 
 
 EXPECTED_HOSTS=("minime" "raspberrypi")
@@ -38,6 +38,12 @@ die () {
 ok () {
     tput bold; tput setaf 10; echo -en "\u2714  " 1>&2; tput sgr0
     tput bold; echo "$*" 1>&2; tput sgr0
+}
+
+cleanup () {
+    echo
+    sudo umount -l "${DESTINATION_NAS_MNT}"
+    die "Aborted"
 }
 
 check_host () {
@@ -125,5 +131,5 @@ echo "elapsed time: ${elapsed_time}"
 echo
 diskspace
 echo
-umount "${NAS_MNT2}"
+sudo umount -l "${DESTINATION_NAS_MNT}"
 ok "backup complete"
