Update git scripts with fixes and better instructions

diff --git a/bin/git-syncrepo b/bin/git-syncrepo
--- a/bin/git-syncrepo
+++ b/bin/git-syncrepo
@@ -4,14 +4,25 @@
 #
 # git-syncrepo - GitHub remote repo sync
 #
-#  - syncs git branches on a remote fork from their parent repo
-#  - only syncs git branches that have a local counterpart
-#  - only works if inside a local git repo that was cloned from a fork
-#  - requires GitHub CLI (https://github.com/cli/cli/blob/trunk/docs/install_linux.md)
+# - syncs git branches on a remote fork from their parent repo
+# - only syncs git branches that have a local counterpart
+# - only works if inside a local git repo that was cloned from a fork
+# - requires GitHub CLI (https://github.com/cli/cli/blob/trunk/docs/install_linux.md)
+#
+# usage:
+#  - set an environment variable named `GITHUB_USERNAME` with your GitHub account name:
+#    - i.e.: `export GITHUB_USERNAME=cgoldberg`
+#  - add this script to a directory on your PATH
+#  - make this script executable (chmod +x git-syncrepo)
+#  - run `git syncrepo` from any directory in a local git repo
 
-GITHUB_USERNAME="cgoldberg"
+set -e
 
 die() { echo "$*" 1>&2 ; exit 1; }
+
+if [ ! -n "${GITHUB_USERNAME}" ]; then
+    die "fatal: GITHUB_USERNAME environment variable not set"
+fi
 
 if [ ! -x "$(command -v git)" ]; then
     die "fatal: can't find git"
@@ -19,6 +30,10 @@ fi
 
 if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
     die "fatal: not a git repository"
+fi
+
+if [ ! -x "$(command -v gh)" ]; then
+    die "fatal: can't find GitHub CLI. follow installation instructions at: https://github.com/cli/cli"
 fi
 
 repo=$(basename $(basename $(git remote get-url origin)) ".git")
