Update script headers

diff --git a/bin/git-sync b/bin/git-sync
--- a/bin/git-sync
+++ b/bin/git-sync
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
-# Corey Goldberg
 #
-# pull all local git branches in current repo
+# Corey Goldberg (https://github.com/cgoldberg)
+#
+# git-sync - rebase all local git branches in current repo from remote tracking branches
+#
 #  - stashes uncommitted changes
 #  - switches to default branch and does pull/rebase
 #  - switches to every other local branch and does pull/rebase
@@ -12,9 +14,14 @@ set -e
 
 die() { echo "$*" 1>&2 ; exit 1; }
 
-if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
-    die "not in a git repo"
+if [ ! -x "$(command -v git)" ]; then
+    die "fatal: can't find git"
 fi
+
+if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
+    die "fatal: not a git repository"
+fi
+
 echo
 current_branch=$(git branch --show-current)
 default_branch=$(git remote show origin | sed -n "/HEAD branch/s/.*: //p")
