enforce root when upgrading squeezebox

diff --git a/bin/squeezeboxserver-upgrade b/bin/squeezeboxserver-upgrade
--- a/bin/squeezeboxserver-upgrade
+++ b/bin/squeezeboxserver-upgrade
@@ -13,13 +13,19 @@ set -e
 base_version='7.9.1'
 
 
+if [[ $EUID -ne 0 ]]; then
+  echo "permission denied."
+  echo "$(basename $0) must be run as root."
+  exit 1
+fi
+
 echo "starting Squeezebox Server upgrade..."
 lms_old_installed_version=$(apt-cache show logitechmediaserver | grep "Version" | cut -d " " -f 2)
 echo "found existing LMS installation: ${lms_old_installed_version}"
 
 echo "killing all running versions of LMS"
-sudo killall squeezeboxserver > /dev/null 2>&1
-sudo killall squeezeboxserver_safe > /dev/null 2>&1
+killall squeezeboxserver > /dev/null 2>&1
+killall squeezeboxserver_safe > /dev/null 2>&1
 
 echo "finding latest LMS ${base_version} beta release"
 latest_deb_url=$(curl -s "http://www.mysqueezebox.com/update/?version=${base_version}&revision=1&geturl=1&os=deb")
@@ -40,7 +46,7 @@ done
 printf "\r"
 
 echo "installing: ${latest_deb}"
-sudo dpkg -i "${tmp_dir}/${latest_deb}" > /dev/null 2>&1 || { echo "installation FAILED" && exit 1; }
+dpkg -i "${tmp_dir}/${latest_deb}" > /dev/null 2>&1 || { echo "installation FAILED" && exit 1; }
 
 echo "cleaning up after installation"
 rm -rf "${tmp_dir}"
@@ -48,3 +54,4 @@ rm -rf "${tmp_dir}"
 lms_installed_version=$(apt-cache show logitechmediaserver | grep "Version" | cut -d " " -f 2)
 echo "update of LMS ${base_version} from ${lms_old_installed_version} to ${lms_installed_version} is complete!"
 echo "please restart Squeezebox Server"
+echo "done"
